export const chains = [
  {
    chainId: 1,
    name: "Ethereum",
    currency: "ETH",
    explorerUrl: "https://etherscan.io",
    rpcUrl: "https://cloudflare-eth.com",
  },
  {
    chainId: 11155111,
    name: "Sepolia",
    currency: "ETH",
    explorerUrl: "https://sepolia.etherscan.io",
    rpcUrl: "https://rpc.sepolia.org",
  },
  {
    chainId: 137,
    name: "Polygon",
    currency: "MATIC",
    explorerUrl: "https://polygonscan.com",
    rpcUrl: "https://polygon-rpc.com",
  },
  {
    chainId: 56,
    name: "Binance Smart Chain",
    currency: "BNB",
    explorerUrl: "https://bscscan.com",
    rpcUrl: "https://bsc-dataseed.binance.org",
  },
  {
    chainId: 100,
    name: "Gnosis Chain (xDai)",
    currency: "XDAI",
    explorerUrl: "https://blockscout.com/xdai/mainnet",
    rpcUrl: "https://rpc.gnosischain.com",
  },
  {
    chainId: 43114,
    name: "Avalanche",
    currency: "AVAX",
    explorerUrl: "https://snowtrace.io",
    rpcUrl: "https://api.avax.network/ext/bc/C/rpc",
  },
  {
    chainId: 10,
    name: "Optimism",
    currency: "ETH",
    explorerUrl: "https://optimistic.etherscan.io",
    rpcUrl: "https://mainnet.optimism.io",
  },
  {
    chainId: 42161,
    name: "Arbitrum One",
    currency: "ETH",
    explorerUrl: "https://arbiscan.io",
    rpcUrl: "https://arb1.arbitrum.io/rpc",
  },
  {
    chainId: 250,
    name: "Fantom",
    currency: "FTM",
    explorerUrl: "https://ftmscan.com",
    rpcUrl: "https://rpc.ftm.tools",
  },
  {
    chainId: 42220,
    name: "Celo",
    currency: "CELO",
    explorerUrl: "https://explorer.celo.org",
    rpcUrl: "https://forno.celo.org",
  },
  {
    chainId: 1284,
    name: "Moonbeam",
    currency: "GLMR",
    explorerUrl: "https://moonbeam.moonscan.io",
    rpcUrl: "https://rpc.api.moonbeam.network",
  },
  {
    chainId: 324,
    name: "ZkSync Era",
    currency: "ETH",
    explorerUrl: "https://explorer.zksync.io",
    rpcUrl: "https://mainnet.era.zksync.io",
  },
  {
    chainId: 8453,
    name: "Base",
    currency: "ETH",
    explorerUrl: "https://basescan.org",
    rpcUrl: "https://mainnet.base.org",
  },
];
